- project/AppDependencies.scala
DL-8303
**Maintenance** 
Upgrade the hmrc-mongo dependency to latest version
In light of other upgrades we have kept this change to minimum so have not applied any other updates
> DL-8303 hmrc-mongo dependency upgrade

- app/views/sections/businessOnOwnAccount/FollowOnContractView.scala.html
- test/assets/messages/FollowOnContractMessages.scala
- test/views/sections/businessOnOwnAccount/FollowOnContractViewSpec.scala
PR for ATs: https://github.com/hmrc/off-payroll-acceptance-tests/pull/174
> DL-7552: migrate FollowOnContractView, update tests

- project/AppDependencies.scala
- project/plugins.sbt
DL-8387
**Maintenance** 
Play upgrade to 2.8.16
Bootstrap upgrade to 5.25.0
No other updates applied as upgrade is also in progress which has already upgraded other dependencies and will be going into Production in the near future
> DL-8387 play and boostrap upgrade

- app/views/sections/exit/OfficeHolderView.scala.html
- test/assets/messages/OfficeHolderMessages.scala
- test/views/sections/exit/OfficeHolderViewSpec.scala
> DL-6872 - Refactor Office Holder page

- app/views/sections/setup/WhatDoYouWantToDoView.scala.html
- test/views/sections/setup/WhatDoYouWantToDoViewSpec.scala
> DL-7580 Refactor WhatDoYouWantToDo page

- app/views/sections/setup/WorkerUsingIntermediaryView.scala.html
- test/views/ViewSpecBaseNew.scala
- test/views/sections/setup/WorkerTypeViewSpec.scala
> DL-7583 Refactor worker type view page

- app/views/results/sections/letter/letter_about_this_result_box.scala.html
- conf/application-json-logger.xml
- project/AppDependencies.scala
- test/assets/messages/results/DecisionVersionMessages.scala
- test/views/results/ResultViewFixture.scala
> DL-6867 govuk template upgrade

- app/views/components/input_radio_new.scala.html
- app/views/sections/control/ChooseWhereWorkView.scala.html
- test/views/behaviours/ViewBehavioursNew.scala
- test/views/sections/control/ChooseWhereWorkViewSpec.scala
> DL-6871 Refactor ChooseWhereWorkView

- app/views/sections/setup/ContractStartedView.scala.html
- test/views/sections/setup/ContractStartedViewSpec.scala
Migrate ContractStartedView onto the new play-frontend-hmrc library
PR for ATs: https://github.com/hmrc/off-payroll-acceptance-tests/pull/197
> DL-7577 - Migrate ContractStartedView

- app/views/results/sections/contact_details_new.scala.html
> DL-6866 Migrate contact details

- app/views/results/undetermined/AgentUndeterminedView.scala.html
- test/assets/messages/results/UndeterminedDecisionMessages.scala
- test/views/results/AgentUndeterminedViewSpec.scala
DL-6869 Agent Undetermined Page Migration
**New feature** 
govuk template upgrade. ATs not included as I ran them and they passed
> DL-6869 Agent Undetermined Page Migration

- app/views/sections/setup/AgencyAdvisoryView.scala.html
- test/views/sections/setup/AgencyAdvisoryViewSpec.scala
DL-7576 Signed branch
Migrated AgencyAdvisory view, should be signed
> DL-7576 Signed branch

- app/views/sections/setup/IntermediaryView.scala.html
- test/assets/messages/IntermediaryMessages.scala
- test/views/sections/setup/IntermediaryViewSpec.scala
#DL-7578 Migrated Intermediary View
**New feature** 
Migrated Intermediary View, running all necessary tests
> DL-7578 Migrated Intermediary View

- app/views/templates/ErrorTemplate.scala.html
DL-6877 Error Template GovUk migration
> DL-6877 Error Template GovUk migration

- app/views/sections/control/ScheduleOfWorkingHoursView.scala.html
- test/views/sections/control/ScheduleOfWorkingHoursViewSpec.scala
Migrated ScheduleOfWorkingHours view and associated unit tests.
> DL-7564 Migrated ScheduleOfWorkingHours view

- build.sbt
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- project/scaffold.sbt
- test/views/behaviours/YesNoViewBehavioursNew.scala
Upgrade play-frontend-hmrc to latest version 6.0.0
Fix deprecation warning in build.sbt
Dependency updates
> DL-9348 4.1.0 play-frontend-hmrc

- app/views/results/inside/IR35InsideView.scala.html
- test/assets/messages/results/InDecisionMessages.scala
- test/views/results/IR35InsideViewSpec.scala
> DL-7529: Migrated IR35Inside View

- app/views/results/undetermined/IR35UndeterminedView.scala.html
- test/assets/messages/results/UndeterminedDecisionMessages.scala
- test/views/results/IR35UndeterminedViewSpec.scala
Migrated IR35Undetermined view
> DL-7549: Migrated IR35Undetermined view

- app/views/components/teal_resultNew.scala.html
- app/views/results/undetermined/PAYEUndeterminedView.scala.html
- test/assets/messages/results/UndeterminedDecisionMessages.scala
- test/views/results/PAYEUndeterminedViewSpec.scala
Migrated PAYEUndetermined view
> DL-7550 - Migrated PAYEUndetermined view

- app/views/sections/financialRisk/MaterialsView.scala.html
- test/views/sections/financialRisk/MaterialsViewSpec.scala
Migrated Materials view, including unit tests and acceptance tests - see PR 205
> DL 7566 - Migrated Materials view

- app/views/results/sections/pdf/decision_versionNew.scala.html
DL-7548 Migration for PDF Directory: decision_version
**New feature** 
Created new file (decision_versionNew.scala.html) to replace old file (decision_version.scala.html)
> DL-7548 Migration for decision_version

- app/views/sections/financialRisk/OtherExpensesView.scala.html
- test/views/sections/financialRisk/OtherExpensesViewSpec.scala
Migrated OtherExpenses view including unit tests and acceptance tests - see PR 206 in the Off-Payroll acceptance tests.
> DL 7567 - Migrated OtherExpenses view

- app/views/sections/financialRisk/MaterialsView.scala.html
Removal of errant bracket (related to migration of Materials view).
> DL-7566 removal of errant bracket (related to migration of Materials view)

- app/views/sections/financialRisk/PutRightAtOwnCostView.scala.html
- test/views/sections/financialRisk/PutRightAtOwnCostViewSpec.scala
Migrate PutRightAtOwnCost
Fix unit tests
Note - separate ATs to support this PR:
https://github.com/hmrc/off-payroll-acceptance-tests/pull/207
> DL-7568 Migrated PutRightAtOwnCost view

- app/views/sections/personalService/DidPaySubstituteView.scala.html
- test/views/sections/personalService/DidPaySubstituteViewSpec.scala
Migrated DidPaySubstitute view, including fixing unit tests and acceptance tests - see PR 210.
> DL 7572 Migrated DidPaySubstitute view

- app/views/sections/partParcel/LineManagerDutiesView.scala.html
- test/views/sections/partParcel/LineManagerDutiesViewSpec.scala
Migrate LineManagerDutuesView
Fix unit tests
Note - separate ATs to support this PR:
https://github.com/hmrc/off-payroll-acceptance-tests/pull/211
> DL-7571 migration of LineManagerDutuesView

- app/views/sections/personalService/NeededToPayHelperView.scala.html
- test/views/sections/personalService/NeededToPayHelperViewSpec.scala
Migrate NeededToPayHelperView
Fix unit tests
Note - separate ATs to support this PR:
https://github.com/hmrc/off-payroll-acceptance-tests/pull/212
> DL-7573 migration of NeededToPayHelperView page

- app/views/BusinessOnOwnAccountSectionChangeWarningView.scala.html
- test/views/BusinessOnOwnAccountSectionChangeWarningSpec.scala
... and fix tests
No AT changes required for this one as there is no sub header present
> DL-7587 migrate BusinessOnOwnAccountSectionChangeWarningView page

- app/views/PersonalServiceSectionChangeWarningView.scala.html
- test/views/PersonalServiceSectionChangeWarningSpec.scala
.. and fix tests
No AT changes required as there is no sub header with this one
> DL-7592 migrate PersonalServiceSectionChangeWarningView page

- conf/messages.cy
- test/resources/welshMessages/messages.cy
Changes made to conf/messages.cy and welshMessages/messages.cy files
Unit tests and it tests run without errors
ATs run without any errors
> DL-9372 update changes to reflect His Majestys Revenue and Customs

- app/testonly/views/feature_switch.scala.html
Feature switch migration and update classes
> DL-10401 migration of feature switch view

- project/AppDependencies.scala
Reverting some dependencies that are causing issues in environment when attempting to render the service
> DL-6881dep reverting some dependencies

- app/assets/stylesheets/print_preview.css
Adding snippet to make look of printed output more consistent across browsers
Screen shots of main browsers on ticket for reference
> DL-10070 update print preview css with max column width

- app/forms/AdditionalPdfDetailsFormProvider.scala
- app/models/AdditionalPdfDetails.scala
- app/views/AddDetailsView.scala.html
- app/views/components/input_textarea_new.scala.html
- conf/messages.cy
- conf/messages.en
- test/controllers/PDFControllerSpec.scala
- test/forms/AdditionalPdfDetailsFormProviderSpec.scala
- test/resources/welshMessages/messages.cy
- test/services/EncryptionServiceSpec.scala
- test/views/results/ResultViewFixtureNew.scala
**Bug fix**
Fixes include translation and repositioning of the error messages on the page as well as hints etc. Also fixed the unit tests.
> DL 10562 - Fixes for the Add Details page

- app/views/results/inside/officeHolder/OfficeHolderIR35View.scala.html
To test PDF file in staging environment as concept before making changes to all other result views
> DL-10433 switch PDF view for OfficeHolderIR35View

- app/views/results/inside/officeHolder/OfficeHolderIR35View.scala.html
No changes to PR bot comments as these will be addressed by subsequent PR for scala upgrade
> revertDL-10433 reimplement PDF switch for OfficeHolderIR35View
